blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://discord.gg/Q3peDrPG95
    about: If you have a "How do I?" question please ask in the our Discord (https://discord.gg/Q3peDrPG95)