on: issue_comment

name: Chimoney Bot

permissions:
  issues: write
  contents: read

jobs:
  check_comments:
    name: Check comments for /chimoney_pay
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: chimoney_pay
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin

      - name: Act on the command
        run: echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i

      - name: Run Node.js script
        id: node-script
        run: |
          response=$(node index '${{ steps.command.outputs.command-arguments }}')
          echo "::set-output name=response::$response"
        
      - run: echo "Response is ${{ steps.node-script.outputs.response }}"

      - name: Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ steps.node-script.outputs.response }}
