name: Update Contributors

on:
  push:
    branches:
      - main  

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bash
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Update Contributors
        run: |
          bash update_contributors.sh
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"

      - name: Commit changes
        run: |
          git commit -am "Update contributors"
          git push origin main
